# Generated by Django 6.0.3 on 2026-03-29 05:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('meals', 'Meals & Entertainment'), ('office', 'Office Supplies'), ('software', 'Software & Subscriptions'), ('training', 'Training & Development'), ('other', 'Other')], db_index=True, default='other', max_length=50, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(db_index=True, verbose_name='Expense Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('current_step', models.PositiveSmallIntegerField(default=1, help_text='Tracks which approval level is active in the workflow.', verbose_name='Current Approval Step')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(help_text='1 = first approver, 2 = second, etc.', verbose_name='Step Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional note left by the approver.', verbose_name='Comment')),
                ('action_date', models.DateTimeField(blank=True, help_text='Populated automatically when the approver acts.', null=True, verbose_name='Action Date')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='expenses.expense', verbose_name='Expense')),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
                'ordering': ['expense', 'step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'status', '-created_at'], name='expense_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'current_step'], name='expense_status_step_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approver', 'status'], name='appr_stat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('expense', 'step_number')},
        ),
    ]
