# Generated by Django 6.0.3 on 2026-03-29 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/%Y/%m/', verbose_name='Receipt Image')),
                ('image_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hex digest of uploaded image bytes.', max_length=64)),
                ('is_duplicate', models.BooleanField(default=False, help_text='True when another scan with the same image_hash already exists.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial — low confidence'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True, default='', verbose_name='Raw OCR Text')),
                ('confidence', models.FloatField(default=0.0, help_text='0.0–1.0 heuristic score.')),
                ('extracted_merchant', models.CharField(blank=True, default='', max_length=200)),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('extracted_currency', models.CharField(blank=True, default='', max_length=10)),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('extracted_description', models.TextField(blank=True, default='')),
                ('amount_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Converted Amount (INR)')),
                ('exchange_rate', models.FloatField(blank=True, help_text='1 {currency} = X INR at scan time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_scan', to='expenses.expense', verbose_name='Linked Expense')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_scans', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Receipt Scan',
                'verbose_name_plural': 'Receipt Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.IntegerField(help_text='ID of the linked Expense (denormalised).')),
                ('ocr_amount_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('submitted_amount_inr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discrepancy_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('discrepancy_pct', models.FloatField(blank=True, help_text='Absolute % difference.', null=True)),
                ('fraud_signal', models.CharField(choices=[('none', 'No discrepancy'), ('amount_gap', 'Submitted amount differs from OCR'), ('duplicate', 'Duplicate receipt image detected'), ('low_conf', 'OCR confidence too low to verify')], db_index=True, default='none', max_length=20)),
                ('flagged_for_review', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='receipts.receiptscan')),
            ],
            options={
                'verbose_name': 'Receipt Audit',
                'verbose_name_plural': 'Receipt Audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
